# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5b375d315a553f0ed46bf437a709e1b9"
name = "tien-dev-test-2"
application_url = "http://localhost:8080"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "http://localhost:8080/auth/callback",
  "http://localhost:8080/auth/shopify/callback",
  "http://localhost:8080/api/auth/callback"
]
