client_id = "5b375d315a553f0ed46bf437a709e1b9"
name = "tien-dev-test-2"
application_url = "https://ellen-regard-prefix-productive.trycloudflare.com/app"
embedded = true

[webhooks]
api_version = "2026-01"
subscriptions = [ { compliance_topics = [ "shop/redact", "customers/redact", "customers/data_request" ], uri = "https://ellen-regard-prefix-productive.trycloudflare.com/webhook" }, { topics = [ "app/uninstalled" ], uri = "https://ellen-regard-prefix-productive.trycloudflare.com/webhook" } ]

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [ "https://ellen-regard-prefix-productive.trycloudflare.com/auth/callback" ]

[access]
admin = { embedded_app_direct_api_access = true }
